### 

GET http://localhost:3000/index

### 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "password": "123456"
}

### 

POST http://localhost:3000/auth/singin
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "password": "123456",
    "preferences": ["comerce", "sports", "politics", "myLittlePony"],
    "ages": ["18-25", "36-45"],
    "lenguages": ["Peruano", "español", "aleman"],
    "name":"Jesus"
}

### 

POST http://localhost:3000/auth/delete
Content-Type: application/json

{
    "id":"679b40a734ad9250cacd6eed",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWI0MGE3MzRhZDkyNTBjYWNkNmVlZCIsImVtYWlsIjoiamR6YzE1MTFAZ21haWwuY29tIiwiaWF0IjoxNzM4MjI4MDEwfQ.BF17-vnwqXCzi-Y-fSzDuMpHcyu1an00pCN4wSa_klA"
}

### 

POST http://localhost:3000/auth/getUser
Content-Type: application/json

{
    "id": "678632e9e5964fd651dbf880",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODYzMmU5ZTU5NjRmZDY1MWRiZjg4MCIsImVtYWlsIjoiamR6YzE1MTFAZ21haWwuY29tIiwiaWF0IjoxNzM2ODQ4NjM5LCJleHAiOjE3MzY4NTIyMzl9.GPTqzg0M7K-_7Q3_GmS8QKhkEeH-Ukza53k-Mnrz_VI"
}

### 

POST http://localhost:3000/auth/updateLocation
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTQ2NjFhZmVmZjg2ZGVlMDhjYmI0NSIsImVtYWlsIjoicGVkcm9AZ21haWwuY29tIiwiaWF0IjoxNzM4ODg4MDQwfQ.GbWkTV9LhbM9-hJLQAyGyl_565AmRxke2YhgdKNZ9eg",
    "city":"Maturín",
    "state":"Monagas",
    "country":"Venezuela",
    "longitude":"8232.21",
    "latitude":"232.12"
}

### 

POST http://localhost:3000/auth/deleteLocation
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OWI0MGE3MzRhZDkyNTBjYWNkNmVlZCIsImVtYWlsIjoiamR6YzE1MTFAZ21haWwuY29tIiwiaWF0IjoxNzM4MjI3ODgzfQ.Vsp-Q4vHbmeMEHD6bztty7Bx0L8CNx-oADkqgvlM2uU"
}

###

###

POST http://localhost:3000/auth/searchBy
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTRkOTc4M2Q5ZmJmYTVlMmYwYjUxZCIsImVtYWlsIjoiamR6YzE1MTFAZ21haWwuY29tIiwiaWF0IjoxNzM3ODA5NjY4fQ.jFduktIoyQOa3QMh11J-rSRxCz929iq7_8bKfmOYbF4",
    "zone": "comerce",
    "zoneFilterLevel": "country",
    "category": "preferences",
    "value": "politics"
}


###

POST http://localhost:3000/chat/createChat
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTQ2NjBhZmVmZjg2ZGVlMDhjYmIzZiIsImVtYWlsIjoiamR6YzE1MTFAZ21haWwuY29tIiwiaWF0IjoxNzM4ODM2NDY5fQ.FD7Ln6pE0TRx4XCrqBMG8xaIZOIQz_E4I_jbdBJsfFw",
    "id":"67a46613feff86dee08cbb42"
}